---
- hosts: all
  remote_user: ansible
#  become: yes
#  become_method: sudo

  tasks:
    - name: uninstall apache
      yum:
        name: httpd
        state: absent

  tasks:
    - name: remove files
      file: 
        path: /var/www/html
        state: absent
