---
- hosts: all
  remote_user: ansible
#  become: yes
#  become_method: sudo

  tasks:

    - name: httpd is stopped
      service:
        name: httpd
        state: stopped

    - name: file delete
      file:
        path: /var/www/html/
        state: absent

    - name: uninstall apache
      yum:
        name: httpd
        state: absent
