---
- hosts: rhelTarget
  remote_user: ansible
  become: yes

  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest

#    - name: latest index. html file is present
#      copy: src=./files/rhDojoSample01.html dest=/var/www/html/index.html

#    - name: latest index. html file is present
#      copy: src=./files/ryoma.JPG dest=/var/www/html/


    - name: httpd is started
      service:
        name: httpd
        state: started

    - name: start firewalld
      command: systemctl start firewalld.service

    - name: open 80
      command: firewall-cmd --zone=public --add-service=http --permanent

    - name: restart firewall
      command: firewall-cmd --reload

